name: CMake

on:
  push:
    branches-ignore:
    - 'wip.*'
    - 'pr.*'
    tags:
    - 'v*'
  release:
    types: [published, created, released]
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.OLYSEUS_BOT_SSH_PRIVATE_KEY }}
        submodules: true

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: ${{github.workspace}}/app/build/outputs/apk/release/*.apk
        asset_name: ${{matrix.asset_name}}
        tag: ${{github.ref}}
        overwrite: true
        file_glob: true
